// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1DO1UYIFl-Tr4dFGUtrBC5fxXvGctxV8',
    appId: '1:652384629019:web:cfc450621e767ff648e3be',
    messagingSenderId: '652384629019',
    projectId: 'foodapp-1154d',
    authDomain: 'foodapp-1154d.firebaseapp.com',
    storageBucket: 'foodapp-1154d.appspot.com',
    measurementId: 'G-8VR0V02KH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4HJmfVi1cuvBPI5T5Y3_vgR_5xMdIbNY',
    appId: '1:652384629019:android:933cb9d70da96c2748e3be',
    messagingSenderId: '652384629019',
    projectId: 'foodapp-1154d',
    storageBucket: 'foodapp-1154d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhN3UaRUa96tNy7MUi5_zRbxjdlGZjlKg',
    appId: '1:652384629019:ios:6656586b74512bcb48e3be',
    messagingSenderId: '652384629019',
    projectId: 'foodapp-1154d',
    storageBucket: 'foodapp-1154d.appspot.com',
    iosClientId: '652384629019-t3h8f4acvgccumv9f75c9ipsm5atqkon.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhN3UaRUa96tNy7MUi5_zRbxjdlGZjlKg',
    appId: '1:652384629019:ios:6656586b74512bcb48e3be',
    messagingSenderId: '652384629019',
    projectId: 'foodapp-1154d',
    storageBucket: 'foodapp-1154d.appspot.com',
    iosClientId: '652384629019-t3h8f4acvgccumv9f75c9ipsm5atqkon.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );
}
